export const users = [
    {
        id: 1,
        name: "Alex Johnson",
        email: "alex.johnson@email.com",
        signupDate: "2025-09-12",
        resumesCreated: 12,
        resumesDownloaded: 8,
        plan: "Premium",
        revenue: 19.99,
        status: "Active",
    },
    {
        id: 2,
        name: "Maria Chen",
        email: "maria.chen@email.com",
        signupDate: "2025-09-14",
        resumesCreated: 7,
        resumesDownloaded: 6,
        plan: "Basic",
        revenue: 9.99,
        status: "Active",
    },
    {
        id: 3,
        name: "David Patel",
        email: "david.patel@email.com",
        signupDate: "2025-09-10",
        resumesCreated: 4,
        resumesDownloaded: 2,
        plan: "Free",
        revenue: 0,
        status: "Inactive",
    },
    {
        id: 4,
        name: "Emma Rodriguez",
        email: "emma.rodriguez@email.com",
        signupDate: "2025-09-08",
        resumesCreated: 18,
        resumesDownloaded: 17,
        plan: "Premium",
        revenue: 29.99,
        status: "Active",
    },
    {
        id: 5,
        name: "Ryan Smith",
        email: "ryan.smith@email.com",
        signupDate: "2025-09-11",
        resumesCreated: 3,
        resumesDownloaded: 1,
        plan: "Free",
        revenue: 0,
        status: "Banned",
    },
];
