export const activitySummary = [
    {
        id: 1,
        label: "Active Users (7 days)",
        value: 856,
        change: "+12%",
        trend: "up",
    },
    {
        id: 2,
        label: "Resumes Created (This Week)",
        value: 1942,
        change: "+8%",
        trend: "up",
    },
    {
        id: 3,
        label: "Resumes Downloaded (This Week)",
        value: 1480,
        change: "+5%",
        trend: "up",
    },
    {
        id: 4,
        label: "New Paid Upgrades",
        value: 128,
        change: "-3%",
        trend: "down",
    },
];

export const activeUsersTableData = [
    {
        id: 1,
        name: "Alex Johnson",
        email: "alex.johnson@email.com",
        plan: "Premium",
        resumesCreated: 12,
        resumesDownloaded: 10,
        lastActive: "2025-10-18 10:32 AM",
        totalActions: 24,
    },
    {
        id: 2,
        name: "Maria Chen",
        email: "maria.chen@email.com",
        plan: "Basic",
        resumesCreated: 10,
        resumesDownloaded: 8,
        lastActive: "2025-10-18 09:50 AM",
        totalActions: 20,
    },
    {
        id: 3,
        name: "David Patel",
        email: "david.patel@email.com",
        plan: "Free",
        resumesCreated: 8,
        resumesDownloaded: 5,
        lastActive: "2025-10-17 07:28 PM",
        totalActions: 15,
    },
    {
        id: 4,
        name: "Emma Rodriguez",
        email: "emma.rodriguez@email.com",
        plan: "Premium",
        resumesCreated: 18,
        resumesDownloaded: 17,
        lastActive: "2025-10-18 11:02 AM",
        totalActions: 35,
    },
    {
        id: 5,
        name: "Ryan Smith",
        email: "ryan.smith@email.com",
        plan: "Free",
        resumesCreated: 6,
        resumesDownloaded: 4,
        lastActive: "2025-10-16 05:15 PM",
        totalActions: 10,
    },
];

export const recentActivityFeed = [
    {
        id: 1,
        user: "Alex Johnson",
        action: "Created a new resume",
        timeAgo: "3m ago",
        icon: "🧾",
    },
    {
        id: 2,
        user: "Maria Chen",
        action: "Upgraded to Premium",
        timeAgo: "1h ago",
        icon: "💎",
    },
    {
        id: 3,
        user: "David Patel",
        action: "Downloaded a resume PDF",
        timeAgo: "2h ago",
        icon: "📥",
    },
    {
        id: 4,
        user: "Emma Rodriguez",
        action: "Edited profile information",
        timeAgo: "4h ago",
        icon: "👤",
    },
];
